added meteor version 2.9.1
disney/meteor-base pull request #131
Opened 2023-01-05 18:06 UTC by gerwinbrunner

Hi, since meteor 2.9.1 is out, I forked this repo and run:
`./update.sh --meteor-version 2.9.1 --node-version 14.21.2`

Finally, I created this PR

2023-01-05 18:42 UTC, diavrank requested changes
I suggest you run first the script with version 2.9.0, make a commit and after run the script with 2.9.1. This is to include all the Meteor versions.

2023-01-05 18:42 UTC, diavrank commented on .github/workflows/continuous-integration-workflow.yml
> +          - '2.9.1'
add 2.9.0
```suggestion
          - '2.9.0'
          - '2.9.1'
```

2023-01-05 18:42 UTC, diavrank commented on versions.sh
> +	'2.9.1'
```suggestion
	'2.9.0'
	'2.9.1'
```

2023-01-05 18:42 UTC, diavrank commented on support.sh
> +	elif [[ "$1" == 2.9.1 ]]; then node_version='14.21.2'
```suggestion
	elif [[ "$1" == 2.9.0 ]]; then node_version='14.21.2'
	elif [[ "$1" == 2.9.1 ]]; then node_version='14.21.2'
```

2023-01-06 05:03 UTC, GeoffreyBooth commented
> I suggest you run first the script with version 2.9.0, make a commit and after run the script with 2.9.1. This is to include all the Meteor versions.

Yes, please include 2.9.0 as well.

2023-01-08 20:52 UTC, diavrank commented
@GeoffreyBooth I've created a PR with both versions

2023-01-12 22:30 UTC, GeoffreyBooth commented
Closed by #132.

2023-01-12 22:30 UTC, closed without merging